[project]
name = "confluence2markdown"
version = "0.1.0"
description = "Convert html export from confluence to markdown"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markitdown>=0.0.1a3",
]
